var annotated_dup =
[
    [ "KA", "namespace_k_a.html", [
      [ "RectF", "struct_k_a_1_1_rect_f.html", "struct_k_a_1_1_rect_f" ],
      [ "Sounds", "class_k_a_1_1_sounds.html", "class_k_a_1_1_sounds" ],
      [ "Vec2D", "struct_k_a_1_1_vec2_d.html", "struct_k_a_1_1_vec2_d" ]
    ] ],
    [ "Animatable", "struct_animatable.html", "struct_animatable" ],
    [ "Animator", "class_animator.html", "class_animator" ],
    [ "Background", "class_background.html", "class_background" ],
    [ "BaseGUI", "class_base_g_u_i.html", "class_base_g_u_i" ],
    [ "BrontoBurt", "class_bronto_burt.html", "class_bronto_burt" ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "ClickableObject", "class_clickable_object.html", "class_clickable_object" ],
    [ "Cloneable", "class_cloneable.html", "class_cloneable" ],
    [ "Collision", "struct_collision.html", "struct_collision" ],
    [ "Door", "class_door.html", "class_door" ],
    [ "Enemy", "class_enemy.html", "class_enemy" ],
    [ "GameLoop", "class_game_loop.html", "class_game_loop" ],
    [ "GameObject", "class_game_object.html", "class_game_object" ],
    [ "GraphicsScene", "class_graphics_scene.html", "class_graphics_scene" ],
    [ "HotHead", "class_hot_head.html", "class_hot_head" ],
    [ "HUD", "class_h_u_d.html", null ],
    [ "Impulse", "struct_impulse.html", "struct_impulse" ],
    [ "Kirby", "class_kirby.html", "class_kirby" ],
    [ "lastmov", "structlastmov.html", "structlastmov" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "MovablePlatform", "class_movable_platform.html", "class_movable_platform" ],
    [ "NetworkObject", "class_network_object.html", "class_network_object" ],
    [ "Node", "class_node.html", "class_node" ],
    [ "ObjectsHolder", "class_objects_holder.html", "class_objects_holder" ],
    [ "Particle", "class_particle.html", "class_particle" ],
    [ "PauseGUI", "class_pause_g_u_i.html", null ],
    [ "PoppyBrosJr", "class_poppy_bros_jr.html", "class_poppy_bros_jr" ],
    [ "Projectile", "class_projectile.html", "class_projectile" ],
    [ "RenderableObject", "class_renderable_object.html", "class_renderable_object" ],
    [ "RigidBody", "class_rigid_body.html", "class_rigid_body" ],
    [ "ScoreItem", "class_score_item.html", null ],
    [ "Serializable", "class_serializable.html", "class_serializable" ],
    [ "Serializer", "class_serializer.html", null ],
    [ "Sparky", "class_sparky.html", "class_sparky" ],
    [ "Terrain", "class_terrain.html", "class_terrain" ],
    [ "TerrainSloped", "class_terrain_sloped.html", "class_terrain_sloped" ],
    [ "TextureManager", "class_texture_manager.html", "class_texture_manager" ],
    [ "TickableObject", "class_tickable_object.html", "class_tickable_object" ],
    [ "VectorField", "class_vector_field.html", "class_vector_field" ],
    [ "WaddleDee", "class_waddle_dee.html", "class_waddle_dee" ],
    [ "WaddleDoo", "class_waddle_doo.html", "class_waddle_doo" ],
    [ "Water", "class_water.html", "class_water" ]
];